name: Build images and add to ghcr.io upon release
on:
  release:
    types:
      - published

jobs:
  proxy:
    name: Push pg image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: pg-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository_owner }}/pgtwool,enable=true
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest
            type=sha

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.pg
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ${{ steps.pg-meta.outputs.tags }}
          labels: ${{ steps.pg-meta.outputs.labels }}

  db2:
    name: Push db2 image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: db2-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository_owner }}/dbtwool,enable=true
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest
            type=sha

      - name: Build and push dbtwool images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.db2
          push: true
          platforms: 'linux/amd64'
          tags: ${{ steps.db2-meta.outputs.tags }}
          labels: ${{ steps.db2-meta.outputs.labels }}
